config/routes.rb
ReviewBrowser::Engine.routes.draw do
  extend ReviewBrowser::Concerns::Routing

  root :to => 'home#index'

  post 'outlet', :to=>"outlet#create"

  resources :reviews do
    resources :notes
    resources :tasks
  end
end

app/models/review_browser/comment.rb
module ReviewBrowser
  class Comment < ActiveRecord::Base
    attr_accessible :body, :review_id, :type
  
    belongs_to :review
    
    validates_uniqueness_of :type, :scope => [:review_id]
    validates_presence_of :review_id
  end
end

app/models/review_browser/comments/general.rb
module ReviewBrowser
  module Comments
    class General < Comment

    end
  end
end

app/models/review_browser/comments/manager.rb
module ReviewBrowser
  module Comments
    class Manager < Comment
    

    end
  end
end

app/models/review_browser/company.rb
module ReviewBrowser
  class Company < ActiveRecord::Base
    attr_accessible :city, :country, :name
    
    has_many :reviews
    validates_presence_of :name
  end
end

app/models/review_browser/concerns/routing.rb
module ReviewBrowser
  module Concerns
    ##
    # The Routing concern makes it easier to write more DRY routes.rb files.
    #
    module Routing
      extend ActiveSupport::Concern

      ##
      # Creates a readable route for Kaminari's pagination system.
      #
      # @param [Symbol] action
      #
      def route_pagination(action = :index)
        get('page/:page', :action => action, :on => :collection)
      end
    end # Routing
  end # Concerns
end # ReviewBrowser

app/models/review_browser/domain.rb
module ReviewBrowser
  class Domain < ActiveRecord::Base
    attr_accessible :name
    
    has_many :opinion_expressions
    validates_presence_of :name
    validates_uniqueness_of :name
  end
end

app/models/review_browser/hotel.rb
module ReviewBrowser
  class Hotel < ActiveRecord::Base
    attr_accessible :city, :country, :name
  end
end

app/models/review_browser/note.rb
module ReviewBrowser
  class Note < ActiveRecord::Base
    attr_accessible :body, :review_id
    
    belongs_to :review
    validates_presence_of :review_id
  end
end

app/models/review_browser/opinion_expression.rb
module ReviewBrowser
  class OpinionExpression < ActiveRecord::Base
    attr_accessible :body, :review_id, :sentiment, :domain_id

    belongs_to :review
    belongs_to :domain
    
    validates_presence_of :review_id

    def same_domain
      RelatedOpinionsFinder.for(self)
    end
    alias :related :same_domain
        
    def self.positive
      where(:sentiment => "positive")
    end
    
    def self.negative
      where(:sentiment => "negative")
    end
  end
end

app/models/review_browser/rating.rb
module ReviewBrowser
  class Rating < ActiveRecord::Base
    attr_accessible :review_id, :topic, :value

    belongs_to :review

    validates_uniqueness_of :topic, :scope => [:review_id]
    validates_presence_of :review_id

    def stars
      value / 20
    end
  end
end

app/models/review_browser/review.rb
module ReviewBrowser
  class Review < ActiveRecord::Base
    #Reviewer Data
    attr_accessible :age_group, :recommend, :trip_type, :visit_date, :visit_reason,
                    :reservation_number, :reviewer_type

    attr_accessible :company_id, :review_id, :source_name, :sentiment
    attr_accessible :title, :language, :manager_response, :review_date, :review_id

    has_many :ratings
    has_many :comments

    has_one :general_comment, :class_name => Comments::General
    has_one :manager_comment, :class_name => Comments::Manager

    has_one :reviewer
    has_many :notes
    has_many :tasks
    has_one :starred_review
    has_many :opinion_expressions
    belongs_to :company

    validates_uniqueness_of :review_id
    validates_presence_of :company_id

    def starred
      !!self.starred_review || false
    end

    def find(*args)
      find_by_review_id(*args)
    end

    def related_reviews(*domains)
      domains = domains.flatten
      company = Company.find(self.company_id)
      company.
      reviews.
      joins(:opinion_expressions).
      group("review_browser_reviews.review_id").
      order("review_date DESC").
      where("review_browser_opinion_expressions.domain_id IN (?)", domains.map(&:id))
    end

    def related_opinion_expressions(*domains)
      domains = domains.flatten
      self.opinion_expressions.where(:domain_id => domains.map(&:id))
    end

    def self.exclude(review)
      where("review_browser_reviews.id != ?", review.id)
    end

    def analyze
      response = Analyzer.analyze(general_comment.body)
      puts response
      update_attribute(:request_id, response["request_id"])
    end
  end
end

app/models/review_browser/reviewer.rb
module ReviewBrowser
  class Reviewer < ActiveRecord::Base
    attr_accessible :location, :name, :review_id
    
    belongs_to :review
    
    validates_presence_of :review_id
  end
end

app/models/review_browser/starred_review.rb
module ReviewBrowser
  class StarredReview < ActiveRecord::Base
    attr_accessible :review_id
    
    belongs_to :review
    
    validates_presence_of :review_id
  end
end

app/models/review_browser/task.rb
module ReviewBrowser
  class Task < ActiveRecord::Base
    attr_accessible :body, :email, :review_id
    
    belongs_to :review
    
    validates_presence_of :review_id
  end
end

app/controllers/review_browser/application_controller.rb
module ReviewBrowser
  class ApplicationController < ActionController::Base
    protect_from_forgery
  end
end

app/controllers/review_browser/home_controller.rb
module ReviewBrowser
  class HomeController < ApplicationController
    
    def index
    end
    
    def show
    end
    
    
  
  end
end

app/controllers/review_browser/notes_controller.rb
module ReviewBrowser
  class NotesController < ApplicationController
    before_filter :get_review

    def new
      @note = @review.notes.new
    end

    def create
      @note = @review.notes.new(params[:note])
      if @note.save
        flash[:succes] = "Note saved"
        respond_to do |format|
          format.html { redirect_to review_path(@review) }
          format.js {render :partial=>"notes"}
        end
      else
        render :action=>:new
      end
    end

    private

    def get_review
      @review = Review.find(params[:review_id])
    end
  end
end

app/controllers/review_browser/outlet_controller.rb
module ReviewBrowser
  class OutletController < ApplicationController
    skip_before_filter :verify_authenticity_token

    def create
      review = Review.find_by_request_id(params[:request_id])
      parsed_review = parser.parse(params[:input])

      review.opinion_expressions.destroy_all

      parsed_review.opinions.each do |opinion|
        domain = Domain.find_or_create_by_name(opinion.domain)
        expression = OpinionExpression.create(:body=>opinion.text,
                                              :sentiment=>opinion.sentiment,
                                             :domain_id=>domain.id)
        review.opinion_expressions << expression
      end
      review.general_comment.update_attribute(:parsed_body, parsed_review.html)

      render :text=>"Created", :status=>201
    end

    def parser
      ReviewBrowser::KafToReviewParser.new
    end

  end
end

app/controllers/review_browser/reviews_controller.rb
module ReviewBrowser
  class ReviewsController < ApplicationController
    def show
      if params[:domains]
        domains = params[:domains].split(",") || []
        @domains = Domain.find_all_by_name(domains)
      else
        @domains = Domain.all
      end

      @other_domains = Domain.all - @domains

      @review = Review.find(params[:id])
      @related_reviews = @review.related_reviews(@domains).exclude(@review).first(4)
    end
  end
end

app/controllers/review_browser/tasks_controller.rb
module ReviewBrowser
  class TasksController < ApplicationController
    before_filter :get_review

    def new
      @task = @review.tasks.new
    end

    def create
      @task = @review.tasks.new(params[:task])
      if @task.save
        flash[:succes] = "Task saved"
        respond_to do |format|
          format.html { redirect_to review_path(@review) }
          format.js {render :partial=>"tasks"}
        end
      else
        render :action=>:new
      end
    end

    private

    def get_review
      @review = Review.find(params[:review_id])
    end
  end
end

app/views/layouts/review_browser/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Olery Review Browser</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
    <%= stylesheet_link_tag "review_browser/application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div class="container">
      <%=yield%>
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <%= javascript_include_tag 'review_browser/application'%>
    <!-- Latest compiled and minified JavaScript -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/review_browser/notes/_note.html.haml
=link_to nil, :class=>"list-group-item" do
  %p=note.body

app/views/review_browser/notes/_notes.html.haml
=render(@review.notes) || "No notes created"

app/views/review_browser/notes/new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= simple_form_for [@review, @note], :remote=>true, :data=>{:'update-target'=>"#notes-list"} do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">New note</h4>
      </div>
      <div class="modal-body">
        <%=f.input :body, :label=>false, :input_html=>{:cols=>80, :rows=>5} %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">close</button>
        <button type="submit" class="btn btn-primary">save changes</button>
      </div>
    </div><!-- /.modal-content -->
  <% end %>
</div><!-- /.modal-dialog -->

app/views/review_browser/reviews/_notes_modal.html.erb
<div class="modal fade" id="notesModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div><!-- /.modal -->

app/views/review_browser/reviews/_tasks_modal.html.erb
<div class="modal fade" id="tasksModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div><!-- /.modal -->

app/views/review_browser/reviews/notes_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="mymodallabel" aria-hidden="true"> </div><!-- /.modal -->

app/views/review_browser/reviews/show.html.haml
.row
  .col-md-4.col-md-offset-3
    - @domains.each do |domain|
      =link_to domain.name.humanize.downcase, review_path(@review, :domains=>domain.name), :class=>"label label-success"
    - @other_domains.each do |domain|
      =link_to domain.name.humanize.downcase, review_path(@review, nil, :domains=>domain.name), :class=>"label label-default"
    =link_to "all", nil, :class=>"label label-default"
  .col-md-2
    .navigate.pull-right
      =link_to "previous", review_path(params[:id].to_i-1, :domains=>params[:domains]), :class=>"btn btn-xs btn-primary"
      =link_to "next", review_path(params[:id].to_i+1, :domains=>params[:domains]), :class=>"btn btn-xs btn-primary"

.row
  .col-md-3.left-bar
    %section#review
      %h4 Review
      %table.table
        %tr
          %th Source
          %td=@review.source_name.humanize
        %tr
          %th Publish Date
          %td=@review.review_date.to_s(:long)
        %tr
          %th Month of stay
          %td=l @review.visit_date, :format=>:month

    %section#ratings
      %h4 Rating details
      %table.table
        -@review.ratings.each do |rating|
          %tr
            %th=rating.topic.capitalize
            %td=star(rating.stars)

    %section#author
      %h4 Author
      %table.table
        %tr
          %th Name
          %td=@review.reviewer.name
        %tr
          %th Location
          %td=@review.reviewer.location
        %tr
          %th Contributions
          %td=rand(10)+1

  .col-md-6
    %h1.page-header
      = @review.title
      %span.glyphicon.glyphicon-star.star.pull-right{ :class=> ("active" if @review.starred)}
      %small
        %span.date=@review.review_date.to_s(:long)
    -if @other_domains.size > 0
      %h3 Review summary on #{@domains.map(&:name).join(", ")}
    -else
      %h3 Review summary
    .well
      .row
        -if @review.related_opinion_expressions(@domains).count > 0
          .positive.col-md-6
            - @review.related_opinion_expressions(@domains).positive.each do |opinion_expression|
              %blockquote=quotify(opinion_expression.body)
          .negative.col-md-6
            - @review.related_opinion_expressions(@domains).negative.each do |opinion_expression|
              %blockquote=quotify(opinion_expression.body)
        -else
          .cold-md-12
            %span No specific sentiments on #{@domains.map(&:name).join(", ")}
    %small=link_to "show all sentiments (#{@review.opinion_expressions.count})", review_path(@review)
    %hr/
    .review-comment
      %h3 Review text
      %p.text
        -if @review.general_comment.parsed_body
          =@review.general_comment.parsed_body.gsub(/(&nbsp;){2,}?/,'').html_safe
          -#=@review.general_comment.parsed_body.html_safe
        -else
          =@review.general_comment.body
    %hr/
    .related-reviews
      %h3 Related reviews
      .row
        -@related_reviews.each do |review|
          .related.col-md-6
            %div{:class => review.related_opinion_expressions(@domains).first.sentiment}
              %blockquote
                =link_to quotify(review.related_opinion_expressions(@domains).first.body), review_path(review, :domains=>params[:domains])
                %small
                  ="#{review.reviewer.name}, #{review.review_date.to_s(:short)}"
  .col-md-3.right-bar
    %section#actions
      %h4 Actions
      %ul.list-group
        %li.list-group-item
          %span.glyphicon.glyphicon-font
          =link_to "Translate"
        %li.list-group-item
          %span.glyphicon.glyphicon-repeat
          =link_to "Change sentiment"
        %li.list-group-item
          %span.glyphicon.glyphicon-share-alt
          =link_to "Send to colleague"
        %li.list-group-item
          %span.glyphicon.glyphicon-pencil
          =link_to "Respond"
    %section#notes
      %h4
        Notes
        =link_to "New note", new_review_note_path(@review),
          :class=>"btn btn-primary btn-xs pull-right",
          :data=>{:toggle=>"modal",
                  :target=>"#notesModal"}
      .list-group#notes-list=render :partial=>"review_browser/notes/notes"

    %section#tasks
      %h4
        Tasks
        =link_to "New task", new_review_task_path(@review),
          :class=>"btn btn-primary btn-xs pull-right",
          :data=>{:toggle=>"modal",
                  :target=>"#tasksModal"}
      .list-group#tasks-list=render(@review.tasks) || "No tasks assigned"

=render "notes_modal"
=render "tasks_modal"

app/views/review_browser/reviews/show_static.html.haml
.row
  .col-md-6.col-md-offset-3
    %span.label.label-success Cleanliness
    - ["Value","Location","Rooms","Service"].each do |label|
      =link_to label, nil, :class=>"label label-default"
    .navigate.pull-right
      =link_to "previous", nil, :class=>"btn btn-xs btn-primary"
      =link_to "next", nil, :class=>"btn btn-xs btn-primary"

.row
  .col-md-3.left-bar
    %section#review
      %h4 Review
      %table.table
        %tr
          %th Source
          %td TripAdvisor
        %tr
          %th Publish Date
          %td=Date.today.to_s(:long)
        %tr
          %th Month of stay
          %td=1.month.ago.to_date.to_s(:short)

    %section#ratings
      %h4 Rating details
      %table.table
        -["overall","value","rooms","location","cleanliness","service"].each do |rating|
          %tr
            %th=rating.capitalize
            %td=random_stars

    %section#author
      %h4 Author
      %table.table
        %tr
          %th Name
          %td Peter Boermans
        %tr
          %th Location
          %td Amsterdam
        %tr
          %th Contributions
          %td=rand(10)+1

  .col-md-6
    %h1.page-header
      Very, very, very inferior!!
      %span.glyphicon.glyphicon-star.star.pull-right
      %small
        %span.date=Date.today.to_s(:long)
    %h3 Review summary
    .well
      .row
        .positive.col-md-6
          %blockquote ``...the bathroom was very clean...''
        .negative.col-md-6
          %blockquote ``...my bedsheets were not changed...''
          %blockquote ``...the room was not cleaned very well...''
    %hr/
    .review-comment
      %h3 Review text
      %p
        I stayed on this Hotel for 3 nights. The hotel looks modern superficially.
        But the service and breakfast in particular are in big question mark.
        <span class="topic">My bed sheets were not changed</span>, <span class="topic">the room was not cleaned very well</span>, except for <span class="topic">the bathroom, which was very clean</span>.
        As this hotel caters for large overseas bus groups there were long time
        consuming lines at reception. The hotel is a long way from the city centre,
        only one restaurant nearby, so your only option is to take the metro to
        get anywhere. Fortunately, the metro is 5 minutes away.
        Casa 400 has a business model: rooms appear as cheap when you want to
        book, but you have to take into account that breakfast is not
        included (€15). Want to have your breakfast in the vicinity? Good luck.
    %hr/
    .related-reviews
      %h3 Related reviews
      .row
        .related.col-md-6
          .positive
            %blockquote
              =quotify("this is positive quote")
              %small="Peter Boermans, "+rand(20).days.ago.to_s(:short)
        .related.col-md-6
          .positive
            %blockquote
              =quotify("this is positive quote")
              %small="Peter Boermans, "+rand(20).days.ago.to_s(:short)
        .related.col-md-6
          .positive
            %blockquote
              =quotify("this is positive quote")
              %small="Peter Boermans, "+rand(20).days.ago.to_s(:short)
        .related.col-md-6
          .negative
            %blockquote
              =quotify("this is negative quote")
              %small="Peter Boermans, "+rand(20).days.ago.to_s(:short)
  .col-md-3.right-bar
    %section#actions
      %h4 Actions
      %ul.list-group
        %li.list-group-item
          %span.glyphicon.glyphicon-font
          =link_to "Translate"
        %li.list-group-item
          %span.glyphicon.glyphicon-repeat
          =link_to "Change sentiment"
        %li.list-group-item
          %span.glyphicon.glyphicon-share-alt
          =link_to "Send to colleague"
        %li.list-group-item
          %span.glyphicon.glyphicon-pencil
          =link_to "Respond"
    %section#notes
      %h4
        Notes
        =link_to "New note", nil, :class=>"btn btn-primary btn-xs pull-right"
      .list-group
        =link_to nil, :class=>"list-group-item" do
          %h5.list-group-item-heading Note number 1
          %p Lorem Lipsum ...
        =link_to nil, :class=>"list-group-item" do
          %h5.list-group-item-heading Note number 2
          %p Lorem Lipsum ...
        =link_to nil, :class=>"list-group-item" do
          %h5.list-group-item-heading Note number 3
          %p Lorem Lipsum ...

    %section#tasks
      %h4
        Tasks
        =link_to "New Task", nil, :class=>"btn btn-primary btn-xs pull-right"
      .list-group
        =link_to nil, :class=>"list-group-item" do
          %h5.list-group-item-heading Task number 1
          %p Lorem Lipsum ...
        =link_to nil, :class=>"list-group-item" do
          %h5.list-group-item-heading Task number 2
          %p Lorem Lipsum ...
        =link_to nil, :class=>"list-group-item" do
          %h5.list-group-item-heading Task number 3
          %p Lorem Lipsum ...

app/views/review_browser/tasks/_task.html.haml
=link_to nil, :class=>"list-group-item" do
  %p=task.body

app/views/review_browser/tasks/_tasks.html.haml
=render(@review.tasks) || "No tasks assigned created"

app/views/review_browser/tasks/new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= simple_form_for [@review, @task], :remote=>true, :data=>{:'update-target'=>"#tasks-list"} do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">New task</h4>
      </div>
      <div class="modal-body">
        <%=f.input :email%>
        <%=f.input :body, :label=>"Task description", :input_html=>{:cols=>80, :rows=>5} %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">close</button>
        <button type="submit" class="btn btn-primary">save changes</button>
      </div>
    </div><!-- /.modal-content -->
  <% end %>
</div><!-- /.modal-dialog -->